server:
  port: 8080

spring:
  application:
    name: healthcare-appointment-management
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Healthcare Appointment Management System
    version: 1.0.0
    description: A healthcare scheduling platform for managing doctor appointments.

logging:
  level:
    root: INFO
    com.cloudnativeplayground.healthcare: DEBUG
